[project]
name = "serialn"
version = "1.0.0"
description = ""
requires-python = ">=3.11"
dependencies = ["click>=8.1"]

[project.scripts]
hi = "serialn:hi"
list_recipes = "serialn:list_recipes"
view_recipe = "serialn:view_recipe"
refresh_recipes = "serialn:refresh_recipes"
add_recipe = "serialn:add_recipe"
remove_recipe = "serialn:remove_recipe"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"