[project]
name = "serialn"
version = "1.0.0"
description = ""
requires-python = ">=3.11"
dependencies = ["click>=8.1"]

[project.scripts]
hi = "serialn:hi"
list-recipes = "serialn:list_recipes"
view-recipe = "serialn:view_recipe"
refresh-recipes = "serialn:refresh_recipes"
add-recipe = "serialn:add_recipe"
remove-recipe = "serialn:remove_recipe"
search-tags = "serialn:search_tags"
add-tags = "serialn:add_tags"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"